"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-09-17 08:42:52.659182

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strava_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('athlete_name', sa.String(length=200), nullable=False),
    sa.Column('access_token', sa.String(length=200), nullable=False),
    sa.Column('refresh_token', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('strokes', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('avg_split_s', sa.Float(), nullable=True),
    sa.Column('avg_spm', sa.Float(), nullable=True),
    sa.Column('max_spm', sa.Float(), nullable=True),
    sa.Column('avg_power_w', sa.Float(), nullable=True),
    sa.Column('max_power_w', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('disconnect_s', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('samples', sa.JSON(), nullable=False),
    sa.Column('strava_upload_id', sa.Integer(), nullable=True),
    sa.Column('strava_activity_id', sa.Integer(), nullable=True),
    sa.Column('strava_status', sa.String(length=16), nullable=False),
    sa.Column('strava_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_client_id'), 'workouts', ['client_id'], unique=True)
    op.create_index(op.f('ix_workouts_started_at'), 'workouts', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workouts_started_at'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_client_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_table('strava_tokens')
    # ### end Alembic commands ###
